# https://github.com/brigade/scss-lint/blob/master/config/default.yml

linters:
    Indentation:
        width: 4
    SelectorFormat:
        convention: hyphenated_BEM
    NestingDepth:
        max_depth: 10 # :(
    SelectorDepth:
        max_depth: 10
    PropertySortOrder:
        enabled: true
        ignore_unspecified: false
        order: smacss
    EmptyLineBetweenBlocks:
        enabled: false
